awsRegion: ${aws_region}

autoDiscovery:
  clusterName: ${eks_cluster_id}
extraArgs:
  aws-use-static-instance-list: true

image:
  repository: 635304352795.dkr.ecr.cn-north-1.amazonaws.com.cn/cluster-autoscaler
  tag: ${image_tag}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
